FROM node:20-alpine AS build
WORKDIR /app
COPY webapp/package*.json ./
RUN npm ci
COPY webapp ./
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm i -g serve
COPY --from=build /app/dist ./dist
EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]